language: go

go:
  - master

env:
  - GO111MODULE=on

before_script:
  - go version

script:
  - go test -v ./... || exit 1
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)



